### ISSUE TITLE
ssd_hc now causing error with multi_ci arg

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/shinyssdtools#25]
the offending code:
```
  ssdtools::ssd_hc(x, proportion = percent / 100, nboot = 10L, min_pboot = 0.8, multi_est = TRUE, multi_ci = FALSE)$est
```
the warning is `Warning: Error in ssd_hc.fitdists: `...` must be unused.`

I think this used to work previously because multi_ci was silently passing through and not used

what is the correct ci_method to use?
this is just to get the estimate and not the bootstrapped CI

**Comment by sebdalgarno** [comment]
using default for now ("weighted_samples")

**Comment by joethorley** [comment]
Yes if just getting the estimate the CI doesn't matter. I would just drop

`multi_ci = FALSE` as no longer correct and also drop `multi_est = TRUE` as now the default (and will eventually become the only option)

**Comment by sebdalgarno** [comment]
done
