### ISSUE TITLE
update user guide

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/shinyssdtools#28]
From @atillmanns 
User Guide | Step 1 - Add reference to Boron dataset
-- | --
User Guide | Step 2 - The second point under step 2, "select or deselect distributions to fit"  Change the text: "Select or deselect the distributions to fit the data.  Note that if two or more similar models fit the data well then the support for this type of shape will be over-inflated.  View the article here for more information".  And then direct the reader to the article on the ssdtools page: https://bcgov.github.io/ssdtools/articles/distributions.html
User Guide | Step 3 - Change title to include percent of species effected
User Guide | Step 3, #1; Add text to highlight the use of the button to calculate HC5 or % species effected
User Guide | Step 4 - Add instructions regarding calculation of CI band (i.e. "R code can be used to calculate CI bands on graphics by changing …"

**Comment by sebdalgarno** [comment]
but there are no French translations? (sent email to @atillmanns)
Perhaps better to get @atillmanns to provide exact English and French text to add, and I will modify the Rmd file

**Comment by sebdalgarno** [comment]
waiting for email response with French and English words to add/modify to Rmd file

**Comment by atillmanns** [comment]
Sent the revised text to Marianne to translate.

**Comment by sebdalgarno** [comment]
boron citation done

**Comment by sebdalgarno** [comment]
done
