### ISSUE TITLE
Add reference to About page

### ISSUE THREAD

**Issue by atillmanns** [poissonconsulting/shinyssdtools#31]
Can you please add this reference to the About page:

For more information on using model averaging to generate HC5 estimates, please see:
Schwarz, C.J. and A.R. Tillmanns. 2019. Improving statistical methods to derive species sensitivity distributions. Water Science Series, WSS2019-07, Province of British Columbia, Victoria.

And here is the hyperlink for the report:
http://a100.gov.bc.ca/appsdata/acat/documents/r57400/2_1568399094009_8398900200.pdf

**Comment by sebdalgarno** [comment]
I've added to English About page. Please provide French translation for
"For more information on using model averaging to generate HC5 estimates, please see:"
