### ISSUE TITLE
Change axis numbering on French plots

### ISSUE THREAD

**Issue by atillmanns** [poissonconsulting/shinyssdtools#32]
For French axis, there is a space between the number and the percentage sign so it should read, "0 %" rather than "0%" as it does on for English axis.  Also, there are no commas to mark thousands, but rather spaces so it should read, "10 000" rather than "10,000".  I pasted the French numbers below:

0 %
20 %
40 %
60 %
80 %
100 %
1
100
10 000
1 000 000
100 000 000

**Comment by sebdalgarno** [comment]
done
