### ISSUE TITLE
Complete the output table on fit page?

### ISSUE THREAD

**Issue by atillmanns** [poissonconsulting/shinyssdtools#33]
The output table on the fit page lists the goodness-of-fit statistics and the weight but not the HC5 estimate, with the standard error, and upper and lower confidence intervals.  Is it possible to include these similar to Table 1 on page 10 of [Schwarz and Tillmanns 2019](http://a100.gov.bc.ca/appsdata/acat/documents/r57400/2_1568399094009_8398900200.pdf)

**Comment by sebdalgarno** [comment]
each dist is now included in the output table of Predict tab, in addition to the average
