### ISSUE TITLE
Why is dotted line for hazard proportion not matching estimated value of 1!

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/shinyssdtools#35]
<img width="2030" alt="Screenshot 2024-09-28 at 13 51 32" src="https://github.com/user-attachments/assets/e9c3c691-d585-4741-887c-60056604d952">

**Comment by joethorley** [comment]
The dotted line is wrong as Elodea canadensis has a value of 1 in the data!

**Comment by joethorley** [comment]
is it a rounding issue?

<img width="759" alt="Screenshot 2024-09-28 at 15 27 31" src="https://github.com/user-attachments/assets/6ec018e7-99cd-4254-a3b5-6d594a1d4b28">

**Comment by sebdalgarno** [comment]
the offending code is here, prior to percent being passed to the plotting function
<img width="604" alt="image" src="https://github.com/user-attachments/assets/24a697bb-d799-4568-8ae2-e09fdcf544e3">

if I remove the rounding I get
Warning: Error in ssdtools::ssd_plot: `hc` must match 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, ... or 0.99, not 0.039.

**Comment by sebdalgarno** [comment]
in this case the percent affected from concentration of 1 is 3.9
this is converted to proportion - 0.039
but 0.039 is not accepted by ssd_plot as needs to be rounded
